### PR TITLE
added IgnoreBody and IgnoreHeaders options to VCRConfig

### PR DESCRIPTION
**Pull request by hexdigest**
Hi, hope you find it useful

### CODE REVIEW

**Comment by seborama** [comment]
Hi Maxim,

Thanks for your nice PR.

This got me thinking about longer term implications and opportunities.

I need to review how hooks work at the moment with a view to investigate a concept of re-usable "recipes" for hooks.

It would help if you could tell me more about your use case.

Regards.

**Comment by hexdigest** [comment]
Hi Seb,

First of all, thank you for your amazing package. I used it to create recording reverse-proxy to use as a standalone tool for testing:
https://github.com/hexdigest/gmeter

Our team uses this tool to mock some third-party services. In order to do this we record every test case we have to a different cassette. The problem is that sometimes there are multiple headers that we need to exclude from matching, or sometimes it's the body that has several JSON parameters that need to be ignored but the only thing that matters is the **order** of the requests and it's pretty boring to define all these exclusion rules and it would be nice to have simple option to completely ignore headers and/or body.

I tested gmeter against this PR by adding -body and -headers command line flags and it worked well for us.

Thanks!

**Comment by seborama** [comment]
Hi,

I've caught up a bit with my thoguhts and what you are trying to do is in fact already supported albeit not via booleans.

Should you not require the headers or body, you can create a dedicated VCRConfig for that purpose:

```go
&govcr.VCRConfig{
    RequestFilterFunc: func(respHeader http.Header, respBody []byte) (*http.Header, *[]byte) {
        return &http.Header{}, &[]byte{}
    },
    ResponseFilterFunc: func(respHeader http.Header, respBody []byte, reqHeader http.Header) (*http.Header, *[]byte) {
        return &http.Header{}, &[]byte{}
    },
    Logging: true,
}
```

This effectively removes the headers and body from the comparison that takes place to match a track. In other words, it ignores the headers and body, just as you intended.

I prefer to avoid code functionality that overlaps to keep the code clearer and simpler. The solution above is simple enough and I'm now considering removing `ExcludeHeaderFunc` too since the same result can be achieved with a `RequestFilterFunc` / `ResponseFilterFunc`, similarly to the example above.

I will add more examples in the source code to document these use-cases.

Best regards.

**Comment by seborama** [comment]
Addendum:
You could generalise the example above for more re-usability as below:

```go
ignoreHeadersAndBody := func() (*http.Header, *[]byte) {
    return &http.Header{}, &[]byte{}
}

vcr := govcr.NewVCR(example4bCassetteName,
    &govcr.VCRConfig{
        RequestFilterFunc: func(respHeader http.Header, respBody []byte) (*http.Header, *[]byte) {
            return ignoreHeadersAndBody()
        },
        ResponseFilterFunc: func(respHeader http.Header, respBody []byte, reqHeader http.Header) (*http.Header, *[]byte) {
            return ignoreHeadersAndBody()
        },
    })
```

**Comment by hexdigest** [comment]
@seborama, got it, thanks!

**Comment by seborama** [comment]
Glad to help and thanks for your interest. Much appreciated. 

Bonne chance.
Seb

**Pull request closed without merging**
